### ISSUE TITLE
[Frontend] Post ID

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#102]
**Describe the bug**
```
interface Post {
    id: string
    epochKey: string
    content: string
    publishedAt: Date
    commentCount: number
    upCount: number
    downCount: number
}
```
但是後端傳來的Post長這樣
<img width="248" alt="image" src="https://github.com/social-tw/social-tw-website/assets/9023842/c3eab981-2003-4648-8b6a-f78ab1029c4f">
導致我發了一篇新的文章後，那篇文章的Post interface裡id為null，因此點擊`Post`不會前往`/posts/${id}`。

**To Reproduce**
1. 註冊
2. 發文
3. 點擊剛剛發佈的那篇文章
4. 會看到只能夠前往`/posts/` 而非`/posts/:id`

**Expected behavior**
1. 註冊
2. 發文
3. 點擊剛剛發佈的那篇文章
4. 前往該文章的PostDetail頁面 `/posts/${_id}`

**Screenshots**
<img width="1180" alt="image" src="https://github.com/social-tw/social-tw-website/assets/9023842/36641995-f766-4803-9c07-d5ed8dbe19cc">

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser: Chrome

**Additional context**
順便請問一下，上圖可見回傳的post結構裡還有一個`postId`，並且也是list of component的key，但由於皆為從0開始的整數，與範例post產生衝突。因此想請問一下
1. 未來會用這個`postId`來辨識post嗎？如果是的話是否要與範例post先做出區隔以免造成bug。
2. 若其實是要用`post._id`來辨識post的話，這個`postId`存在的意義是？

**Comment by Xiawpohr** [comment]
剛剛看了 contract 上的 postId，它代表的是 epochKey 發的第幾篇貼文，因此未來應該不會用 postId 來辨識 post<
之後會統一使用 `post._id`來辨識 post

在 PR 上我已經將範例 post 的 id 會加上 prefix: `demo-` 來和真正的 post 做出區隔。
