### ISSUE TITLE
[contract][Comment] Delete/Edit Comment: to prove 2 epochKey from the same user.

### ISSUE THREAD

**Issue by FoodChain1028** [social-tw/social-tw-website#110]
## Description
After discussing with comment team members, the deleting/edit function for the comment (or even the post) **should emit a delete event to update the comment/post content**. 

## Scenario 1: 
user comment/post at epoch `100` and s/he wants to edit/delete their epoch key in the same epoch. It's relatively simple. We could verify this key with the same epochKeyProof.

## Scenario 2:
user comment/post at epoch `100`, yet s/he wants to edit/delete your content in epoch `107`. Here comes with a problem: **the epochKey would be updated and we could not regenerate the same epochKey. Therefore, it's hard to verify the user identity while editing and deleting the content.**

## Solution
One of the possible solutions of this is to generate a proof that prove 2 epochKey (from different epoch) is generated from the same identity secret without actually recording the relationship among the epochKeys and identity secret.

## Alternatives
Other solutions:
1. limiting the users only update their content in the same epoch period (In my opinion, this is not reasonable for a social media).
2. Storing all past epochKeyProofs.

And this issue might be me overthinking, if there are other solutions/ you do not think this is a issue, please discuss with me. (cc @vivianjeng & @kittybest )

**Comment by vivianjeng** [comment]
I think if currently the Rep is not used to do something related to post/vote
We can simply let the user prove the old epoch key at epoch `100`
And there is a [`epochKeyLiteProof`](https://developer.unirep.io/docs/circuits-api/circuits#epoch-key-lite-proof)
for user to prove he owns the secret to the epoch key

if we need a new epoch key in epoch `107`
we might need another circuits to prove epoch 1 and epoch 2 in a single circuit (to make sure the user doesn't generate two proofs with different id secret)
