### ISSUE TITLE
[relay][vote] implement vote

### ISSUE THREAD

**Issue by chentihe** [social-tw/social-tw-website#121]
**Implement Vote**

In milestone4, we have to implement vote, here's what this milestone should be done

**Vote data will be stored in DB, not on-chain**

1. add a vote api for user to upvote / downvote for the corresponding post
- user is able to upvote / downvote for the corresponding post, the amount of upvote / downvote for the post is one.
- by default, every user will have 3 epoch keys during the current epoch, we should randomly choose the epoch key for the user to do the action(post, vote, comment), and each of them should be used at least one time.
- check epoch key and attesterId before voting
- create / update vote data and update the post data(upCount/downCount)
2. the user is able to cancel the upvote / downvote in either the same epoch or the different epoch.
- in same epoch, just set the upvote / downvote status to `false`
- in different epoch, need to check the identities of these two epoch keys are identical.
3. create a vote schema
```sql
{
  postID: string
  epoch: int
  epoch key: string
  upvote: bool
  downvote: bool
}
```
4. write unit test

**Comment by andy78644** [comment]
> * by default, every user will have 3 epoch keys during the current epoch, we should randomly choose the epoch key for the user to do the action(post, vote, comment), and each of them should be used at least one time.

This means user can vote 3 times at same posts in a epoch ?

**Comment by chentihe** [comment]
> > * by default, every user will have 3 epoch keys during the current epoch, we should randomly choose the epoch key for the user to do the action(post, vote, comment), and each of them should be used at least one time.
> 
> This means user can vote 3 times at same posts in a epoch ?

In practical, one user is only able to vote for the post once with one epoch key. This can be done on frontend to generate all epochKeys to find out the user voted or not. But, how do we do this verification on backend? It seems we can't produce all epochKeys of the user on backend.
