### ISSUE TITLE
[Frontend] flow for adding a Comment 

### ISSUE THREAD

**Issue by badukwei** [social-tw/social-tw-website#123]
**Is your feature request related to a problem? Please describe.**
Create flow and text box for user to leave comments.

**Describe alternatives you've considered**
check below

**Comment by Xiawpohr** [comment]
<img width="201" alt="comment editor" src="https://github.com/social-tw/social-tw-website/assets/13558919/990cfc88-2384-4bbc-a50b-c333b31eae8e">
<img width="125" alt="adding a comment" src="https://github.com/social-tw/social-tw-website/assets/13558919/3e80f1f7-921d-4e9f-a891-8b7d8413d32e">

**Comment by badukwei** [comment]
I am doing this now.
