### ISSUE TITLE
[backend][Comment] comment storage

### ISSUE THREAD

**Issue by NOOMA-42** [social-tw/social-tw-website#127]
**Is your feature request related to a problem? Please describe.**
comment storage in IPFS and backend

**Describe the solution you'd like**
store event output of comment CID in relayer DB，comment + CID also stored in IPFS 

* store event output
* event with a content which is CID (same as post)
* delete event ，a potential solution is to emit add comment event and emit delete comment event. wait for #110 solution

when user post comment, comment first goes into DB and tx sent then DB status modified if tx success else removed
(frontend will display as grey when tx is processing)

**Describe alternatives you've considered**
N/A

**Additional context**
reference: post https://github.com/Unirep/Unirep-Social/blob/2e8e01509a7c6a1aa7f4657666ac006291734eea/packages/backend/src/routes/PostRouter.ts#L374

**Comment by Lisooo790926** [comment]
Complete
