### ISSUE TITLE
[relay][vote] the data of vote table should be preserved for display use

### ISSUE THREAD

**Issue by chentihe** [social-tw/social-tw-website#130]
**Is your feature request related to a problem? Please describe.**

During epoch 1, when a user vote for a post, the upvote/downvote icon will be bold for user to know that s/he already voted.
However, when this epoch ends, we may lost the epoch key of this user so that the upvote/downvote icon may not display properly.

**Describe the solution you'd like**

We should keep all vote data on DB and the properties of `Vote Table` should include `epoch`. Even the epoch ends, we are still able to find out the upvote/downvote of the user by restoring the epochKeys of that epoch on the frontend side.

**Comment by andy78644** [comment]
Why should we store epoch?

**Comment by chentihe** [comment]
> Why should we store epoch?

Because what we discussed before is we will delete all vote data after the epoch ended, however, there's no delete table function on `anondb`. Hence, I use `epoch` property to delete all epoch. But now, we don't delete the vote data, so the `epoch` should be removed from the `Vote` table
