### ISSUE TITLE
[frontend] [comment] comment status notification

### ISSUE THREAD

**Issue by Xiawpohr** [social-tw/social-tw-website#142]
**Is your feature request related to a problem? Please describe.**
notify user their comment status

**Additional context**

<img width="209" alt="comment status" src="https://github.com/social-tw/social-tw-website/assets/13558919/5eac095b-c2f2-4378-8ef6-072e79b8bf77">

<img width="213" alt="comment success" src="https://github.com/social-tw/social-tw-website/assets/13558919/cd3ac34e-f704-4954-a490-644764c4eda4">

**Comment by badukwei** [comment]
Should we create a issue for storing action data

**Comment by Xiawpohr** [comment]
I think storing actions is highly related to action notification. We need to merge these tasks. I will rewrite description of this issue.

**Comment by badukwei** [comment]
Maybe we can finish all three issues then start doing the storing action coding?

**Comment by Xiawpohr** [comment]
Agreed
