### ISSUE TITLE
[frontend] [comment] show comment list for a post

### ISSUE THREAD

**Issue by Xiawpohr** [social-tw/social-tw-website#143]
**Is your feature request related to a problem? Please describe.**
show comment list for a post

**Additional context**

<img width="185" alt="comment list" src="https://github.com/social-tw/social-tw-website/assets/13558919/ab3d8d10-fc6d-4685-8281-44d288fafb2f">

**Comment by badukwei** [comment]
I am wondering if this has been done or not.

**Comment by Xiawpohr** [comment]
I can do this task

**Comment by badukwei** [comment]
Hi, I built the comment form and transaction animation in this branch. Maybe it would help.
https://github.com/social-tw/social-tw-website/tree/feature/comment/frontend/adding-flow
I also create a branch for co-work.
https://github.com/social-tw/social-tw-website/tree/feature/comment/frontend/co-work
And here is the pr.
https://github.com/social-tw/social-tw-website/pull/147
