### ISSUE TITLE
[Bug][UserState] fix unirep app events handler issue

### ISSUE THREAD

**Issue by chentihe** [social-tw/social-tw-website#153]
**Describe the bug**
This issue is to fix [issue 119](https://github.com/social-tw/social-tw-website/issues/119). Although we set `UnirepSocialSynchronizer` to `UserState` to resolve this problem on unit test, this issue may happen on frontend since the type of synchronizer is `Synchronizer` which don't handle `UnirepApp` contract events.
https://github.com/social-tw/social-tw-website/blob/7eca64f5f9d8e722c52f3166ec1c7488a677cae1/packages/frontend/src/contexts/User.tsx#L110-L147

**Describe the solution you'd like**
I refer to [Unirep-Social](https://github.com/Unirep/Unirep-Social), They use [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) to store the data on frontend, however, they don't set the synchronizer to `UnirepSocialSynchronizer`. I was wondering if they can fetch the `UnirepSocial` contract events on frontend.
https://github.com/Unirep/Unirep-Social/blob/c82669cb928cf37ed609fe36e9c34d0208a21b0b/packages/frontend/src/context/User.ts#L258-L282

1. we can choose IndexedDB on frontend to store data
2. Initialize `UserState` by sending `UnirepSocialSynchronizer` to fetch not only `Unirep` contract events but `UnirepApp` contract events.

**Comment by vivianjeng** [comment]
do we need unirep social events?
for the previous unirep social, the events are action related but not reputation related.
so if users generate proofs, they just need to know their reputation.

and if you want to sync a new contract events, you can refer to the `get contracts()` function
https://github.com/Unirep/Unirep-Social/blob/c82669cb928cf37ed609fe36e9c34d0208a21b0b/packages/backend/src/Synchronizer.ts#L69
by overwriting the `get contracts()` function and add handlers, you can sync the events

**Comment by cc03668** [comment]
@chentihe 再確認一次這個問題是否存在，確認沒問題可以把 issue 關掉

**Comment by chentihe** [comment]
2024/5/17 討論過後，目前該問題已不存在，將此issue關閉
