### ISSUE TITLE
[relay] Discuss the folder structure in relay

### ISSUE THREAD

**Issue by Lisooo790926** [social-tw/social-tw-website#165]
**Is your feature request related to a problem? Please describe.**
Currently, we haven't clearly defined the purpose of each folder or the main structure in our relay module.
Should we discuss the basic structure to ensure everyone can follow and implement it?
src
├── routes 
├── services
├── singletons
├── synchornizer.ts
├── types  
└── utils 

**Describe the solution you'd like**
We could first discuss and document the initial version of the folder structure. If there are any better ideas, we can continue to improve it so that everyone can follow.

**Describe alternatives you've considered**

**Additional context**
For future maintenance and improve readability.

**Comment by NOOMA-42** [comment]
Can we discuss "Should we turn IPFS as a service" in this issue?

**Comment by Lisooo790926** [comment]
Hi everyone, the folder structure  
src
├── routes : for controller level
├── services : for business logic level 
        ├── PostService / UserService / CommentService ... 
        ├── singletons : for common usage like  
                ├── TransactionManager / IPFSService / SocketManager / Synchroizer / TransactionHelper .. 
├── types : for customize data class

Is this folder ok?

**Comment by NOOMA-42** [comment]
should IpfsService in Service or singleton? 

> Hi everyone, the folder structure src ├── routes : for controller level ├── services : for business logic level ├── PostService / UserService / CommentService ... ├── singletons : for common usage like ├── TransactionManager / IPFSService / SocketManager / Synchroizer / TransactionHelper .. ├── types : for customize data class
> 
> Is this folder ok?
