### ISSUE TITLE
[Contract] [Relay] Consistent on the CID storing pattern

### ISSUE THREAD

**Issue by ryanycw** [social-tw/social-tw-website#170]
**Describe the bug**

Improve consistency on the CID storage pattern by storing CID in the contract.

**Expected behavior**

- [Store CID in the contract](https://github.com/social-tw/social-tw-website/blob/c1431ae1ba1599a77f19403ba34c1b31d1e4226b/packages/contracts/contracts/UnirepApp.sol#L84)

 - [Send CID as part of the encoded data](https://github.com/social-tw/social-tw-website/blob/c1431ae1ba1599a77f19403ba34c1b31d1e4226b/packages/relay/src/routes/post.ts#L120)

**Comment by cc03668** [comment]
@ryanycw 再確認一次是否已解決，解決的話可以把它關掉

**Comment by ryanycw** [comment]
@FoodChain1028 will pick up this issue :)
