### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by vivianjeng** [social-tw/social-tw-website#23]
Either circleci or github actions
- [x] `yarn && yarn build`
- [x] `yarn circuits test`
- [ ] `yarn contracts test`
- [ ] `yarn relay test` (TODO)
- [ ] `yarn frontend test` (TODO)
- [x] `yarn lint --check`

**Comment by ryanycw** [comment]
@jason-ntu Can you share some information on how we create the image with your dockerfile and push it to ghcr.io

**Comment by ryanycw** [comment]
@jason-ntu I have pushed the image to here and set the CR_PAT
ghcr.io/social-tw/ubuntu-22.04:circom

**Comment by jason-ntu** [comment]
> @jason-ntu Can you share some information on how we create the image with your dockerfile and push it to ghcr.io

Oh! Sorry I didn't see this ><

**Comment by jason-ntu** [comment]
It looks like something about the container went wrong:
https://github.com/social-tw/social-tw-website/actions/runs/5949887767

**Comment by ryanycw** [comment]
This should be solved now. If a further issue is coming up, let's open a new one.
