### ISSUE TITLE
[Frontend] Date display in Profile page is wrong

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#233]
**Describe the bug**
在個人頁面裡點擊**歷史紀錄 ➡️ 貼文** 後，顯示的貼文日期是錯誤的。
試了一下，應該是因為後端傳過來的timestamp (`publishedAt`) 實際上是*string*，然而我們在這邊⬇️
https://github.com/social-tw/social-tw-website/blob/3eacf2272e5fb27bbf8d4111dacceaf5ab79350d/packages/frontend/src/types/api.ts#L14
卻將其當成number，導致`dayjs`套件並不是把它當成unix timestamp去parse。
解決方法是把上面那邊改成*string*後，在⬇️
https://github.com/social-tw/social-tw-website/blob/3eacf2272e5fb27bbf8d4111dacceaf5ab79350d/packages/frontend/src/pages/Profile/History/services/PostService.ts#L53-L54
加上`const timestamp = parseInt(relaySourcePost.publishedAt)`。

**To Reproduce**
- 註冊
- 發文
- 前往個 **Profile ➡️ 歷史紀錄 ➡️ 貼文** ❗️

**Expected behavior**
今天發的文應該就是2024/01/04

**Screenshots**
<img width="604" alt="image" src="https://github.com/social-tw/social-tw-website/assets/9023842/1b1911ea-6e4e-4657-bce5-5dc2d4ffb65f">

**Desktop (please complete the following information):**

-   OS: [macOS]
-   Browser [chrome]

**Comment by cc03668** [comment]
@DylanYang0523 這部分好像是你負責的，可以麻煩你處理嗎～～
