### ISSUE TITLE
[Relay] get /api/post/:id will return 404

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#234]
**Describe the bug**
點進`/post/:id`頁面後總是會出現default畫面，打開F12會看到
<img width="401" alt="GET httpilocalhost800 PostDetail  tsx113 GD" src="https://github.com/social-tw/social-tw-website/assets/9023842/12df2a39-ad09-4430-a349-e17212b1e532">
簡單來說就是**找不到該post**
問題出在這⬇️
https://github.com/social-tw/social-tw-website/blob/3eacf2272e5fb27bbf8d4111dacceaf5ab79350d/packages/relay/src/services/PostService.ts#L235
這邊`postId`改成`_id`就可以了。

**To Reproduce**
- 註冊
- 發文
- 點擊貼文 ❗️

**Expected behavior**
應該要顯示正確的 1) 貼文內容 2) 評論內容 3) 投票結果

**Screenshots**

https://github.com/social-tw/social-tw-website/assets/9023842/128fab8a-682c-4084-a7a6-e2609e1c573a

**Desktop (please complete the following information):**

-   OS: [macOS]
-   Browser [chrome]

**Comment by ryanycw** [comment]
I can start work on this
