### ISSUE TITLE
[Frontend] remove demo comments

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#235]
**Describe the bug**
現在每篇貼文都會有demo comments的身影
<img width="689" alt="image" src="https://github.com/social-tw/social-tw-website/assets/9023842/237263bf-5eaf-4948-a2f6-a7ece2866648">
https://github.com/social-tw/social-tw-website/blob/3eacf2272e5fb27bbf8d4111dacceaf5ab79350d/packages/frontend/src/hooks/useFetchComment.ts#L111
現在測試階段是沒關係，正式上線之後這邊要記得拿掉～

**To Reproduce**
- 註冊
- 發文
- 點進貼文 ❗️

**Expected behavior**
應該要只顯示這篇貼文的留言

**Desktop (please complete the following information):**

-   OS: [macOS]
-   Browser [chrome]

**Comment by ryanycw** [comment]
If anyone is interested in this issue, they can also pick up #59
