### ISSUE TITLE
[Feature] [Post] [Frontend] Add transition animation after user publishes a post

### ISSUE THREAD

**Issue by Xiawpohr** [social-tw/social-tw-website#243]
**Is your feature request related to a problem? Please describe.**
Add transition animation after user publishes a post

**Describe the solution you'd like**

<img width="932" alt="Screenshot_2023-12-31_at_1 53 56_PM" src="https://github.com/social-tw/social-tw-website/assets/13558919/a0692e92-631c-499b-b770-ef7ff98c2f1c">

<img width="296" alt="Screenshot_2023-12-31_at_1 54 37_PM" src="https://github.com/social-tw/social-tw-website/assets/13558919/6cc22510-07ea-4e8a-87a7-8682e84f090b">

**Comment by kittybest** [comment]
I think this issue should also be closed.
