### ISSUE TITLE
[Bug] [Relay] [Contract] postId is always zero

### ISSUE THREAD

**Issue by Xiawpohr** [social-tw/social-tw-website#245]
**Describe the bug**
PostId is always returned 0 from relay and contract after user publish a post.

**To Reproduce**

1. Sign up a account
2. Login
3. Publish 2 post
4. These two posts are linked to `/posts/0` because the postId of these posts is 0.

**Expected behavior**
Every posts should have unique postId.

**Additional context**

I think the problem comes from the contract below. I would like know why postId is depended on epochKey?
<img width="751" alt="postId" src="https://github.com/social-tw/social-tw-website/assets/13558919/2323a647-4451-4ded-af9f-4a4470767853">

**Comment by ryanycw** [comment]
This should be close with #246
