### ISSUE TITLE
[Bug][Relay] random failures in relay

### ISSUE THREAD

**Issue by Lisooo790926** [social-tw/social-tw-website#253]
**Describe the bug**
Running test in relay, there are random failures
- Uncaught CodeError: SDP handshake aborted 
- Timed out while trying to connect 

**To Reproduce**
1. Create PR
2. Keep running relay test 

**Expected behavior**
Test pass

**Screenshots**
https://hackmd.io/Uxm21R0YQnWOZSe9dsUnwg

**Additional context**

**Comment by cc03668** [comment]
目前測試都沒遇到了，之後有發生我們再處理！
