### ISSUE TITLE
[contracts] unirep@2.0.0 verifies state tree root in helpers

### ISSUE THREAD

**Issue by vivianjeng** [social-tw/social-tw-website#255]
**Is your feature request related to a problem? Please describe.**
The contract in published package that verifies state tree root
https://github.com/Unirep/Unirep/blob/main/packages/contracts/contracts/verifierHelpers/EpochKeyVerifierHelper.sol

**Describe the solution you'd like**
Remove 
https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/contracts/contracts/UnirepApp.sol#L140-L149
and 
https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/contracts/contracts/UnirepApp.sol#L188-L197

**Describe alternatives you've considered**

**Additional context**

**Comment by FoodChain1028** [comment]
I will deal with this really soon. And I reckon I should also remove the test for `state tree root test` in 

https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/contracts/test/SignupAndPost.test.ts#L184-L214

and 

https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/contracts/test/Comment.test.ts#L110-L146

I also get another question: Will this check be removed in the future version of contract?

**Comment by FoodChain1028** [comment]
Hi @vivianjeng, just want to confirm, epoch check is also included here 

https://github.com/Unirep/Unirep/blob/e57834c1244e76a1e3e8289b0f92b072c2fc8fb8/packages/contracts/contracts/verifierHelpers/EpochKeyVerifierHelper.sol#L52-L55

should I also delete epoch check in `UnirepApp.sol`?

https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/contracts/contracts/UnirepApp.sol#L134-L138

https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/contracts/contracts/UnirepApp.sol#L182-L186

https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/contracts/contracts/UnirepApp.sol#L243-L247
