### ISSUE TITLE
[contracts] `ProofHasUsed` should be checked in signup tests

### ISSUE THREAD

**Issue by vivianjeng** [social-tw/social-tw-website#256]
**Is your feature request related to a problem? Please describe.**
https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/contracts/test/SignupAndPost.test.ts#L83

Logic in this test is incorrect

**Describe the solution you'd like**
Should submit the same proof and revert by `ProofHasUsed`

**Describe alternatives you've considered**

**Additional context**

**Comment by FoodChain1028** [comment]
Will cope with this first.

**Comment by FoodChain1028** [comment]
I found that reused proof is already checked here: 

https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/contracts/test/SignupAndPost.test.ts#L71-L81

I will rewrite the description to make consistency with the logic
