### ISSUE TITLE
[relay] epoch key should be checked in deleting comment

### ISSUE THREAD

**Issue by vivianjeng** [social-tw/social-tw-website#258]
**Is your feature request related to a problem? Please describe.**
1. It should check if epoch key is different but not invalid proof
https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/relay/test/comment.test.ts#L241
2. If epoch key mismatches epoch key on-chain, the tx will be reverted. we should prevent this.
   https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/relay/src/services/CommentService.ts#L95

**Describe the solution you'd like**
1. should generate epoch key with different nonce (or epoch key not generated by the same person)
2. the comment service should check if the epoch key is the same as stored in db before submitting tx

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanycw** [comment]
I can look into this

**Comment by Lisooo790926** [comment]
Let me check on this~
