### ISSUE TITLE
[frontend] don't hardcode server url

### ISSUE THREAD

**Issue by vivianjeng** [social-tw/social-tw-website#259]
**Is your feature request related to a problem? Please describe.**
If server url changes, it still queries `localhost:8000`
https://github.com/social-tw/social-tw-website/blob/0a9c0b5d4cec920b80e72b51afb993416b83d3bd/packages/frontend/src/hooks/useFetchComment.ts#L23

**Describe the solution you'd like**
Use `SERVER` from config

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanycw** [comment]
Update: This issue also occurred after register with Twitter
![image](https://github.com/social-tw/social-tw-website/assets/63644531/7768bafa-7a58-4e75-b05e-40f6d8e87337)

**Comment by Xiawpohr** [comment]
> Update: This issue also occurred after register with Twitter ![image](https://private-user-images.githubusercontent.com/63644531/299341693-7768bafa-7a58-4e75-b05e-40f6d8e87337.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODUzMTcsIm5iZiI6MTcwNjE4NTAxNywicGF0aCI6Ii82MzY0NDUzMS8yOTkzNDE2OTMtNzc2OGJhZmEtN2E1OC00ZTc1LWIwNWUtNDBmNmQ4ZTg3MzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0Njg5NjZiMDgzM2M3YWRhZTAzN2RjMzZkMDc0NmRlNWExMjIwOTFlMWFlMWM3ZGQ2ODRlNDhlYTk4MGVjZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1UmnTXw9ooF1DEdl0BGoG-I8JEK3hwRGuqnOY7wD9xA)

@ryanycw The reason for the wrong twitter callback url is the incorrect setting of environment variables in production. Please see the codes below for more details

https://github.com/social-tw/social-tw-website/blob/5d8fc07369c1326e66e3dc8c35fb76a4b9928472/packages/relay/src/config.ts#L39-L41

**Comment by ryanycw** [comment]
@chentihe Can you help us check the settings in GCP? Cause on github `SERVER` is set correctly.

**Comment by chentihe** [comment]
I just checked the gcp, it doesn't display any error message
