### ISSUE TITLE
[Enhancement][Relay] Refactor all addActionCount to Synchronizer

### ISSUE THREAD

**Issue by ryanycw** [social-tw/social-tw-website#263]
**Is your feature request related to a problem? Please describe.**
As discussed with @Lisooo790926, move all addActionCount from routes to Synchronizer to improve consistency and atomicness.

**Additional context**
Discussing while working on PR https://github.com/social-tw/social-tw-website/pull/249

**Comment by cc03668** [comment]
@ryanycw 確認問題是否還存在

**Comment by cc03668** [comment]
跟 @chentihe 負責得 [UST-43] 一起處理
