### ISSUE TITLE
[Comment] Should consider postId when deleting comment

### ISSUE THREAD

**Issue by Lisooo790926** [social-tw/social-tw-website#274]
**Describe the bug**
![image](https://github.com/social-tw/social-tw-website/assets/48560984/43e89142-e4eb-4448-859c-5690308fe56b)
`deleteComment` method only get from commendId and status  

**To Reproduce**
NA

**Expected behavior**
`deleteComment` method only should be based on commentId + postId + status since below contract logic
![image](https://github.com/social-tw/social-tw-website/assets/48560984/e1e6c03e-b4ea-4abe-bc7a-e8c190afc234)

**Additional context**

**Comment by kittybest** [comment]
I think this issue is fixed, should be closed.

**Comment by kittybest** [comment]
I think this issue is fixed, should be closed.
