### ISSUE TITLE
[Frontend] Vote process

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#282]
**Describe the bug**
base on `main` branch.
(因為有另一個PR在處理vote的問題，好像會出現不同的bug，因此先就`main` branch上的vote做bug回報。

- 首頁可以vote，但是投完後「不會」把投票按鈕的周圍反白（要重新整理或是點進PostDetail page）
- 進去PostDetail Page才投票的話，雖然該頁面的vote數量更新了，但按上一頁vote數還是沒有改變（還是為0）
- 預期首頁點擊已經投過票的投票按鈕，應該會取消投票，但是實際上會error 
<img width="520" alt="image" src="https://github.com/social-tw/social-tw-website/assets/9023842/a86f86e2-1825-4b01-a69d-6e8f65daa5c3">
- 點進PostDetail Page的話則可順利取消投票，或許在post component的實作上有差異？能否統一呢？
- 那當然也還是有在detail page取消投票後，回到首頁票數沒有更新的情況

完整錄影 ⬇️

https://github.com/social-tw/social-tw-website/assets/9023842/72ba2192-d7c9-4fd0-894a-700368be7531

**To Reproduce**
參考上面的影片

**Expected behavior**
- 首頁的文章上面，按讚/倒讚可以投票，投完票後文章讚數/倒讚數+1，且會顯示user已投票。
- 文章頁面同上，按讚/倒讚可以投票，投完票後文章讚數/倒讚數+1，且會顯示user已投票。
- 若是自己已經有投票的文章：
    - 在已按讚的情況下，按讚會讓讚數-1，兩個按鈕皆無白框
    - 在已按讚的情況下，按倒讚會讓讚數-1、倒讚數+1，倒讚按鈕有白框，讚按鈕無白框
    - 在已按倒讚的情況下，按讚會讓讚數+1、倒讚數-1，讚按鈕有白框，倒讚按鈕無白框
    - 在已按倒讚的情況下，按倒讚會讓倒讚數-1，兩個按鈕皆無白框
    - 並且UI同步更新讚數以及是否已投票的白框
- （最好有個loading bar防止user多次點擊）

**Screenshots**
同上

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser: chrome

**Comment by cc03668** [comment]
請 @UranusLin @DylanYang0523 協助在週會前確認此問題～～
