### ISSUE TITLE
[Frontend] Profile page history

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#283]
**Describe the bug**
做完任何動作後，去Profile>history裡面都無法實時找到紀錄。
https://github.com/social-tw/social-tw-website/assets/9023842/f6addd13-b781-4631-ad36-083131bd4d7d

看起來是不能顯示當前epoch的所有動作紀錄，只能顯示之前epoch的。
並且vote的部分影片內應該是一個正讚一個倒讚，結果兩個都顯示倒讚。

**To Reproduce**
參考上面影片

**Expected behavior**
- 發文、投票、留言後，profile history應該要馬上顯示紀錄 
- （如果我們本來就不讓它顯示當前epoch紀錄的話，應該要在profile history page說明）
- 檢查投票的圖案是否上錯

**Screenshots**
同上

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser: chrome

**Comment by cc03668** [comment]
可以請 @DylanYang0523 在會議前確認此問題嗎？

**Comment by DylanYang0523** [comment]
History 在投票、留言、發文後目前沒有觸發更新，會去新增這部分的功能。

**Comment by DylanYang0523** [comment]
Vote 的 Icon 問題是因為兩邊介面沒有對上，目前已整理修復。
