### ISSUE TITLE
[Frontend] Comment Process

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#284]
**Describe the bug**
- 留言後，留言數量沒有更新
- 點擊首頁留言沒有反應

https://github.com/social-tw/social-tw-website/assets/9023842/43152d67-8722-43d2-a5d1-c654d2d8407b

**To Reproduce**
上面影片

**Expected behavior**
- 點擊首頁「留言」按鈕，可以直接前往post detail page的第一則留言（開放討論）
- 或許Post detail page應該要有個留言的地方？不然身為一個剛開始使用的user，可能不知道要點擊那個留言的button （需要跟Danny討論）
- 留言成功後，post detail page應該要馬上顯示留言
- 留言成功後，不管首頁還是post detail page，應該要更新留言數量
- 留言成功後，點擊右下角的「前往查看」應該要能夠前往該留言

**Screenshots**
同上

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser: chrome

**Additional context**
related [figma](https://www.figma.com/file/WFpSKfe9741XSlXkOXz8s0/Unirep-Social?type=design&node-id=20-8611&mode=design&t=nopT5cq4MB3A8LNL-0)

**Comment by cc03668** [comment]
這問題可以麻煩 @Xiawpohr 協助確認嗎？
