### ISSUE TITLE
[Frontend] Remaining Available Epoch Key Update

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#285]
**Describe the bug**

`3`次內的那個數字並不會更新。
現在確實是寫死的：https://github.com/social-tw/social-tw-website/blob/6859d50b4abe8d3eb98973c750263988e411814a/packages/frontend/src/components/layout/EpochInfo.tsx#L81 

<img width="287" alt="image" src="https://github.com/social-tw/social-tw-website/assets/9023842/b76abb89-fd6b-4364-a5a0-be54e5778eda">

**To Reproduce**

1. Sign up
2. post 
3. check the count

**Expected behavior**
- 那個3應該要改成跟actionCount hook拿資料。

**Comment by cc03668** [comment]
這個我想確認一下，他應該是解釋性文字，而不是提供即時 epoch key 使用次數，但我還是想請 @DylanYang0523 協助更改 copy 讓括弧是全形的可以嗎 🥺

**Comment by kittybest** [comment]
> 這個我想確認一下，他應該是解釋性文字，而不是提供即時 epoch key 使用次數，但我還是想請 @DylanYang0523 協助更改 copy 讓括弧是全形的可以嗎 🥺

誒？那想請問一下具體來說是哪個地方會顯示剩餘次數？我好像在使用過程中沒有注意到

**Comment by Xiawpohr** [comment]
應該不會顯示剩餘次數，上面灰條是用來顯示在當 epoch 的動作次數
