### ISSUE TITLE
[Frontend] View Post/Comment in History

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#286]
**Describe the bug**
Profile > History > 發文/留言 > 前往查看 會前往錯誤的連結
（現在是`/comments/[comment._id]` or `/posts/[post._id]`

https://github.com/social-tw/social-tw-website/assets/9023842/855dafad-b232-4596-bd1a-0ff9f46ad4ed

**To Reproduce**

1. signup
2. publish post
3. leave comment
4. wait for epoch transition and check the history in profile page (related issue: #283)

**Expected behavior**
應該要前往 `/posts/[postid]#[commentid]`

**Comment by cc03668** [comment]
可以請 @DylanYang0523 在會議前確認此問題嗎？如果能盡快處理更好～～麻煩了～～
