### ISSUE TITLE
[Frontend] Signup setIsLogin

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#289]
**Describe the bug**
1. 現在的main branch上，即便註冊成功後，由於`useUser`裡回傳的`isLogin`為false (進一步說，在localStorage裡面的loginStatus為false），因此會一直導回`/welcome`。
2. 並且可能有另一個問題，就是跟relay拿`loginStatus`的時候不是`REGISTERED`，因此又會一直導向註冊頁面，但實際上這個id已經註冊過了，tx都已經送上鏈了，因此又會出現這個id已經註冊過的error。

但是下面這個問題不是一定發生，只有第一個問題一定會產生。

**Expected behavior**
- 註冊
- twitter驗證
- 直接註冊/連接錢包
- 進入首頁，loading bar結束後停留在首頁

**Screenshots**
第一種情況：
https://github.com/social-tw/social-tw-website/assets/9023842/bf0d8023-5488-452b-931b-17b7afebc781
第二種情況：
https://github.com/social-tw/social-tw-website/assets/9023842/eb877794-7478-468e-8a6e-cd0f5a66e892

**Comment by badukwei** [comment]
這邊我再這周末前修一下
