### ISSUE TITLE
Posting Smart Contract Tests

### ISSUE THREAD

**Issue by ryanycw** [social-tw/social-tw-website#31]
Implement the Smart Contracts tests for posting. The following are the tests we discussed.

- [x] Happy Path: Post Success
  - [x] Check Event Emit
- [x] Should fail with wrong proof
  - [x] Check revert with the right message
- [x] Should fail with unsigned up user

Note: All tests should pass CICD

**Comment by FoodChain1028** [comment]
After discussing with @iverJisty, we deem that unit tests in both parts should better separate into different files to avoid conflicts.

**Comment by ryanycw** [comment]
Closing this issue.
