### ISSUE TITLE
Posting Frontend Tests

### ISSUE THREAD

**Issue by ryanycw** [social-tw/social-tw-website#33]
Implement the Frontend tests for posting. The following are the tests we discussed.

- [ ] Should have test scripts
  - [ ] Should succeed to post
  - [ ] Should let user input post contents
  - [ ] Should let user choose epoch keys(or nonces)
  - [ ] Should handle error message and return to correct status 

Note: All tests should pass CICD

**Comment by cc03668** [comment]
This is closed with PR#53
