### ISSUE TITLE
[UST-53] [Frontend] Unify the typing interface of DTO

### ISSUE THREAD

**Issue by cc03668** [social-tw/social-tw-website#330]
**Describe the bug**
- We have the duplicate typing interfaces in `/packages/frontend/src/types` and `/packages/frontend/src/pages/Profile/History/DTO` now.
- 前端之前在協作時因為很多人，所以關於 post 跟 comment 都創建了不同的型別

**Additional context**
Responsible core member: @Xiawpohr 
Story point: 1

**Comment by badukwei** [comment]
剛剛研究了一下，這邊如果要更改成完全統一的格式，其實改動幅度好像還蠻大的，會改到程式碼邏輯，因為這兩個分別是不同的用途，而且分別是不同的 Api 回傳型別，雖然大致上差不多但還是有小部分不同，想問一下統一的程度大概要多統一呢，是會更改到程式碼邏輯的部分，還是說有統一的整理以及定義型別的方式及名稱呢?
