### ISSUE TITLE
Posting Backend Tests

### ISSUE THREAD

**Issue by ryanycw** [social-tw/social-tw-website#35]
Implement the Backend tests for posting. The following are the tests we discussed.

- [x] Should have test scripts
  - [x] Post successfully
  - [x] Should fail if a proof is invalid
  - [x] Should store data correctly
  - [x] Should submit transaction successfully and correctly
  - [x] Should return correct data (success/error messages)

Note: All tests should pass CICD

**Comment by NOOMA-42** [comment]
how do you deal with server started in beforeEach will use duplicate port? Do you have close server method?

**Comment by ryanycw** [comment]
@chentihe Want to discuss with you, sometime this will fail since db doesn't update that fast. Do you have any suggestions to fix this?
https://github.com/social-tw/social-tw-website/blob/3b992e1855de2082de4b3841015a7c38fdf62fe6/packages/relay/test/post.test.ts#L94

**Comment by chentihe** [comment]
maybe you can set synchronizer as a global variable, and call ```synchronizer.waitForSync()``` before you expect the result?
