### ISSUE TITLE
User.ts refactor

### ISSUE THREAD

**Issue by badukwei** [social-tw/social-tw-website#38]
**Is your feature request related to a problem? Please describe.**
Prevent side effect and make sure type safty

**Describe the solution you'd like**
Refactor the User.ts to functional component

**Describe alternatives you've considered**
Create a functional components context for user global states

**Additional context**
Need to solve bugs in merge for posting feature

**Comment by badukwei** [comment]
Needed posting group to deal with the updates

**Comment by ryanycw** [comment]
This issue should be closed by #40
