### ISSUE TITLE
[UST-172] [Relayer]Claim Negative Reputation & API

### ISSUE THREAD

**Issue by FoodChain1028** [social-tw/social-tw-website#385]
## Description

Add a api: `POST /api/reports/claimNegativeReputation` in relayer for frontend to claim negative reputation.

## Details

> 被檢舉者失去 rep，前端拿到所有檢舉案件，一個一個判斷我是不是被檢舉者的 epochKey，是的話，claim 給他 rep，但如果之前有被 claim 過的，就會失敗。（from [Claim reputation in the background](https://www.notion.so/Claim-reputation-in-the-background-c052f41c1d2e4f52b17f1f50ac75a205?pvs=21) discussion part）
> 

Circuit from [Claim Negative Reputation (Circuit)](https://www.notion.so/Claim-Negative-Reputation-Circuit-d131970a998549ce9cbfba15a3af693a?pvs=21)

```
`reportNegRepProof`
public input reported_epoch_key; // if stored on-chain
private input user_id;
private input reported_epoch;
private input current_epoch;
private input current_nonce; // action count
public output current_epoch_key;

for nonce in 0..EPOCH_KEY_NONCE:
  // check one of the reported epoch key is matched
	if reported_epoch_key == poseidon(user_id, reported_epoch, nonce)

current_epoch_key = poseidon(user_id, current_epoch, current_nonce)
```

1. take `[reported_epoch_key, user_id, reported_epoch, current_epoch, current_nonce]` as input
    1. generate `reportedEpochKeyProof` and should be verified in relayer
2. send a transaction with `proof` and `publicSignal` to contract to claim negative reputation for the user
3. change the status of (negative reputation) claimed to `True`.
4. return `200` if succeed. 

## Tests

- should succeed with valid inputs
    - `reportNegRepProof` should be verified
    - sending transaction should pass
    - should return 200 if succeed.
- should revert with wrong userId (given the same nullifier)
- should revert with wrong `reportNegRepProof`
- should revert with wrong epoch

**Comment by UranusLin** [comment]
already merged
