### ISSUE TITLE
[CICD] Error when PR execute build and lint

### ISSUE THREAD

**Issue by Lisooo790926** [social-tw/social-tw-website#45]
**Describe the bug**
Raise error when PR CICD

**To Reproduce**
1. Raise PR
2. Run CI steps
3. check the result 

**Expected behavior**
CI should success

**Screenshots**

**Comment by jason-ntu** [comment]
I have update the cicd node version in this PR (commit [09d45f5](https://github.com/social-tw/social-tw-website/pull/30/commits/09d45f5f7bf95a2e3bdd4040cfbd1bb160ddfe01))

**Comment by Lisooo790926** [comment]
Close this issue, since already been fixed
