### ISSUE TITLE
[UST-193] [Circuit] Improve Proof’s Readability

### ISSUE THREAD

**Issue by cc03668** [social-tw/social-tw-website#450]
## Description

- Add export class for each `Proof` we have in the circuits

## Detail

- There are 3 proofs updated in current project
    - identityProof
    - reportNullifierProof
    - reportNonNullifierProof

However, currently we are using a very naive way to generate the proof and publicSignals. To make these much clear, we can use a `BaseProof` class to make them more readable. 
For example, [`EpochKeyProof`](https://github.com/Unirep/Unirep/blob/main/packages/circuits/src/EpochKeyProof.ts) has several variables to represent what the data in publidSignals actually have:

```tsx
/**
* The index of the data in the public signals
*/
readonly idx = {
epochKey: 0,
stateTreeRoot: 1,
control: 2,
data: 3,
}
// original data
/**
* The epoch key being proved.
*/
public epochKey: bigint
/**
* The state tree root the proof was made against.
* This should be verified to exist onchain when verifying the proof.
*/
public stateTreeRoot: bigint
/**
* The control field used for the proof. This field contains many signals binary encoded into a single 253 bit value. This value is automatically decoded into the other properties on this class.
*/
public control: bigint
/**
* The 32 byte data endorsed by the proof.
*/
public data: bigint
// decoded data
/**
* The nonce used to generate the epoch key. To determine if this value is set check that revealNonce == 1.
*/
public nonce: bigint
/**
* The epoch the proof was made within.
*/
public epoch: bigint
/**
* The attester id for the proof.
*/
public attesterId: bigint
/**
* A number indicating whether the epoch key nonce was revealed in the proof. This value will be either 1 or 0.
*/
public revealNonce: bigint
/**
* The chain id for the proof.
*/
public chainId: bigint
```

### Check Point

1. add the new proof classes in `./circuits`
2. modify
    * [ ] `circuits` tests: add a test for each circuit to make sure that the generated publicSignal and proof is correct.
        * [ ] identityProof
        * [ ] reportNullifierProof
        * [ ] reportNonNullifierProof

**Additional context**
Responsible core member: @FoodChain1028 
Story point: 5

**Comment by Lisooo790926** [comment]
Hi @FoodChain1028 Could you explain more about this issue? 
1. What is purpose of export class in the config, do I need to implement all place to reuse this export? 
2. But there might be 3 (or more) proofs -> what does that mean?

**Comment by FoodChain1028** [comment]
Hi @Lisooo790926 I will update this really soon, since I am still update something with circuit, which would sortly impact this issue.

**Comment by Lisooo790926** [comment]
OK, got it, should I help with any part of this issue? If require, please let me know thanks~

**Comment by FoodChain1028** [comment]
@Lisooo790926 Thank you for your patience :) I have update the information now. So currently `reportNonNullifierProof` is still in a PR (will be soon merged into main). You can start to work on the other two proofs.

**Comment by Lisooo790926** [comment]
ok thanks~
