### ISSUE TITLE
Bug(frontend): the report reason is wrongly displayed

### ISSUE THREAD

**Issue by kittybest** [social-tw/social-tw-website#491]
**Describe the bug**
https://hackmd.io/@w1mYPym0QAeBLhjnIs9tog/rknYSc23A

**Expected behavior**
The displayed reason in the popup report alert should be same as the real report reason classification.

**Screenshots**
see above link

**Desktop (please complete the following information):**

-   OS: [e.g. **iOS**]
-   Browser [e.g. **chrome**, safari]

**Comment by cc03668** [comment]
need access to the hackmd 🙇🏻‍♀️
