### ISSUE TITLE
Bug(frontend): claim rep will cause double user state transition

### ISSUE THREAD

**Issue by vivianjeng** [social-tw/social-tw-website#495]
**Describe the bug**
A post is reported (and others agree the report)
and the author will automatically claim negative reputation
but frontend user state transition will be executed twice
and causes contract error `NullifierAlreadyUsed`

**Expected behavior**
Claim report should wait for previous user state transition success

**Comment by Xiawpohr** [comment]
We suspend to deal with this issue because we cannot reproduce it.

**Comment by kittybest** [comment]
補充error截圖：
<img width="1435" alt="截圖 2024-09-17 晚上7 14 29" src="https://github.com/user-attachments/assets/9d3cfa2e-655a-4a16-8c37-b54d8b401c98">

不知道與這個issue有無相關
