### ISSUE TITLE
[UST-220][Feature][Frontend] Enhance Documentation on X Integration and Data Usage

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#526]
## Description

- 在登入和註冊頁時，將button 中的twitter 修改成X 和加入Ｘlogo，下方加入文字敘述
- 新增多帳號登入選項頁面

UI:
<img width="375" alt="Sign up step1 X" src="https://github.com/user-attachments/assets/109ec9ef-afcf-4174-a2c8-e9dd3095d4b5">
<img width="375" alt="X Log in" src="https://github.com/user-attachments/assets/eb57035e-5173-463d-8a36-6f03c17996b2">

- Story Points: 1
- Reporter: @UranusLin

**Comment by cc03668** [comment]
@UranusLin 請把預期解法、description 補上，謝謝！
