### ISSUE TITLE
[UST-223][Feature][Frontend] Enhance User Feedback for Registration Transaction Completion

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#527]
## Description

- 原本的註冊畫面的loading 動畫在發文區，現在要新增一個彈出視窗顯示loading 進度條和輪播顯示相關內容，當註冊成功後，下方出現新增貼文的按鈕，內容如figma

![Sign up in progress註冊進度](https://github.com/user-attachments/assets/c2028772-8e20-47dd-b6da-038a72409641)
![Sign up in progress註冊進度2](https://github.com/user-attachments/assets/db1fe41c-8f96-47e7-82b5-bd6484b8a13d)
![Sign up in progress註冊進度3](https://github.com/user-attachments/assets/b76b0aee-ccec-4a36-b041-27a11b71fd6d)

**Comment by cc03668** [comment]
@UranusLin 請補齊 description 謝謝！

**Comment by cc03668** [comment]
@Xiawpohr 這個跟 UST226 很有關連，能不能請你一起協助完成這一個 issue 呢？

**Comment by Xiawpohr** [comment]
@cc03668 

在設計圖上，Danny 用「首次註冊的介面導覽」來一次解決以下兩個 issues:
- 🎨 註冊交易完成後，應更有回饋地幫助用戶了解進度以及完成的通知
- 🎨 更有互動性及詳細的 Onboarding 流程，說明計時器、計數器、發文、隨機身份

我認為既然已經在 issue #551 上詳細描述了「首次註冊的介面導覽」，或許可以直接關掉這張 issue，然後可以在 #551 上做後續的討論和補充。

**Comment by cc03668** [comment]
也可以，但 scope 上應該還是會分兩張去紀錄～～是不是可以同一個 pr 一起處理兩個 issue 呢？

**Comment by Xiawpohr** [comment]
可以哦。那這張票一樣也先轉給我，然後我們可以標注一下後續討論都在 #551 上進行。
