### ISSUE TITLE
[UST-224][Feature][Frontend] Enhance Explanation of Direct vs. Wallet Registration Options

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#528]
## Description

- 修改`packages/frontend/src/features/auth/components/AuthNoteDialog/AuthNoteDialog.tsx` 中的敘述如設計
![image (1)](https://github.com/user-attachments/assets/0c98d69a-38c6-4cb0-8642-106d57972b2b)
![image (2)](https://github.com/user-attachments/assets/f7998452-e4cd-4eac-996d-6ada8e33998d)
![image (3)](https://github.com/user-attachments/assets/81a7212c-5f37-45da-a242-5b07bc372ea3)

- story point: 1
- reporter: @UranusLin

**Comment by cc03668** [comment]
@UranusLin description 請補齊

**Comment by kittybest** [comment]
<img width="424" alt="image" src="https://github.com/user-attachments/assets/8d65390d-29aa-4e5b-a7ac-6fcd7967046c">
好像要加上scroll-y
