### ISSUE TITLE
[UST-232][Feature][Frontend] Extend Post-Publish Animation Duration and Add User Controls

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#530]
## Description

- 將跳轉動畫出現時間延長至5秒，在右上角加入關閉按鈕
- change `packages/frontend/src/features/post/components/PostPublishTransition/PostPublishTransition.tsx`

Story point: 1
Reporter: @UranusLin

**Comment by cc03668** [comment]
@UranusLin description 與 notion 不同步
