### ISSUE TITLE
[UST-233][Feature][Frontend] Optimising Action Counter copy

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#531]
## Description

- 修改epoch 計數器中的文字敘述： `packages/frontend/src/features/core/components/EpochInfo/EpochInfo.tsx`

![計數器文案](https://github.com/user-attachments/assets/4f3c5112-392c-4c40-8510-33b0a616febf)

- Story Point: 1
- Reporter: @UranusLin

**Comment by cc03668** [comment]
@UranusLin 請更新 description
