### ISSUE TITLE
[UST-234] [Frontend] Enhance "Transaction" Concept Explanation for Web2 Users

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#532]
## Description

- 依照ui mockup 修改文字敘述如貼文上鏈交易進行中
- 修改 `packages/frontend/src/features/core/components/ActionNotification/ActionNotification.tsx`

![上鏈文案1](https://github.com/user-attachments/assets/82c69577-05df-4780-bfeb-9f8ad73c8b1e)
![上鏈文案2](https://github.com/user-attachments/assets/4729b49b-6dab-42ee-8f42-748e047189cd)
![上鏈文案3](https://github.com/user-attachments/assets/51aaf3c8-9a5c-4f1e-b219-679cfacbbc84)

- Story Point: 1
- Reporter: @UranusLin

**Comment by cc03668** [comment]
@UranusLin 請更新 description
