### ISSUE TITLE
[UST-239][Feature][Frontend] Adjust Comment Layout According to Design Specifications

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#536]
## Description

- 依照原本設計稿調整留言切版縮排
[figma](https://www.figma.com/design/WFpSKfe9741XSlXkOXz8s0/Unirep-Social?node-id=20-8611&node-type=canvas)

### Figma:
![image (4)](https://github.com/user-attachments/assets/8fe3e964-f830-41d0-ab6f-ee050b49411e)
![image (5)](https://github.com/user-attachments/assets/d0a98ac8-2951-4605-9ba3-1f04584a48cc)

---

### Now:
![image (6)](https://github.com/user-attachments/assets/57fed92e-62af-4e62-bff2-812374354fa7)

![image (7)](https://github.com/user-attachments/assets/aacc8844-2996-4365-933c-932143d1f42c)

- Story Point: 1
- Reporter: @UranusLin

**Comment by cc03668** [comment]
@UranusLin 請提供確切設計檔讓開發的人員比較好參考，謝謝
