### ISSUE TITLE
[UST-246][Feature][Frontend] Optimise the copy on the voting page of the report judgement 

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#539]
## Description

- 依照figma設計修改`packages/frontend/src/features/reporting/components/Adjudicate`內的檢舉畫面，像是新增說明畫面，和修改文字敘述

<img width="375" alt="評判流程優化3 (1)" src="https://github.com/user-attachments/assets/13405072-d348-4602-9133-ebe936f6ee57">
<img width="375" alt="評判流程優化4 (1)" src="https://github.com/user-attachments/assets/bc7e206c-bde8-4d00-83d9-7f0908819440">
<img width="375" alt="評判流程優化5 (1)" src="https://github.com/user-attachments/assets/b8afa257-e0a2-4159-95d6-70765f97ac11">
<img width="375" alt="評判流程優化7 (1)" src="https://github.com/user-attachments/assets/e55132c8-6973-4021-9e74-e4c4aea5847d">
<img width="375" alt="評判流程優化8 (1)" src="https://github.com/user-attachments/assets/e85f9671-d6b0-4425-8ef5-3a33675b3d90">
<img width="375" alt="評判流程優化12 (1)" src="https://github.com/user-attachments/assets/cba351b5-cb78-430a-b966-8e09cb7ace0e">

- Story Point: 1
- Reporter: @UranusLin

**Comment by cc03668** [comment]
@UranusLin 請更新 description
