### ISSUE TITLE
[UST-177][Feature][Frontend] Optimise the judging process

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#540]
## Description
- 根據 @Danny 的UIUX 修改前端畫面如文字敘述和新增對應UI之畫面和流程
- 評判按鈕動畫漸進出現，右上角加入x關閉鍵，點擊出現防呆放棄評判
- 點擊前往評判會出現畫面顯示評判說明（如figma
- 投票完出現動畫修改敘述
- 計數器狀態會顯示評判進行中/評判完成敘述
- 檢舉的畫面程式在`packages/frontend/src/features/reporting/components/Adjudicate`和`packages/frontend/src/features/reporting/components/AdjudicateNotification`中
    - `AdjudicateButton.tsx` 加入關閉按鈕
    - `AdjudicateNotification.tsx` 加入動畫，檢舉按鈕由右邊淡入出現
    - `components/Adjudicate`中新增確認投票頁面，文字敘述如figma
    - `components/Adjudicate`中新增點擊前往協助評判後的檢舉說明頁面，畫面文字敘述如figma點擊查看案件詳情進行評判會跳轉到既有畫面

---
Figma: https://www.figma.com/design/WFpSKfe9741XSlXkOXz8s0/Unirep-Social?node-id=3846-8258&node-type=canvas&t=5fZ71yXMPiKi9lie-0
UI: 
![評判流程優化1](https://github.com/user-attachments/assets/0ff8e123-597c-4e4b-90cd-913424c46c7b)
<img width="375" alt="評判流程優化2" src="https://github.com/user-attachments/assets/ba5ec0f9-a0a0-4a41-8ec5-1dd828169ff9">
<img width="375" alt="評判流程優化3" src="https://github.com/user-attachments/assets/52f624ab-0436-4519-84e4-808becbd2c67">
<img width="375" alt="評判流程優化4" src="https://github.com/user-attachments/assets/17c409d9-bb64-4c40-a54b-c6593539edfa">
<img width="375" alt="評判流程優化5" src="https://github.com/user-attachments/assets/bf1a5140-536e-4e3d-b04d-eed97441bfea">
<img width="375" alt="評判流程優化7" src="https://github.com/user-attachments/assets/bfa1c7de-93aa-4bb8-9cc5-9564c632f319">
<img width="375" alt="評判流程優化8" src="https://github.com/user-attachments/assets/047204c3-64bf-4999-8b75-f2baf878339f">
<img width="375" alt="評判流程優化12" src="https://github.com/user-attachments/assets/88c38c03-e34b-4188-8ece-6e909e73f687">

---

Story point: 
Reporter: @UranusLin

**Comment by cc03668** [comment]
@UranusLin Notion 上的 description 更新後，請記得同步到這邊
