### ISSUE TITLE
[UST-252][Feature][Frontend] Simplify Profile Page by Removing Avatar and Reorganizing Information

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#541]
## Description

- 紀錄的項目小標題都有改成中文
（Epoch key除外
- 移除原本的頭貼
- 在點擊我的帳號後會在上面顯示聲譽分數、User id 和帳號創辦日期
- 聲譽分數敘述移到分數下方
- 歷史紀錄貼文將狀態為`被檢舉，審核中`和`已被檢舉並屏蔽`顯示遮蔽

![我的帳號優化1](https://github.com/user-attachments/assets/565a03f3-cf03-40a8-bd39-dfb67d630b6e)
![我的帳號優化2](https://github.com/user-attachments/assets/ce9eddf3-c849-451e-adc1-acb429049ef3)
![我的帳號優化3](https://github.com/user-attachments/assets/f29ce2a1-f2c9-491f-be0d-9ca5a2a5c514)
![我的帳號優化4](https://github.com/user-attachments/assets/55dd05a9-965e-4b26-9049-4ba8bebbfee8)
![我的帳號優化5](https://github.com/user-attachments/assets/7bb86e35-b11a-4c99-b5ba-c544da255e95)

- Story Point: 1
- Reporter: @UranusLin

**Comment by cc03668** [comment]
@UranusLin 請更新 description
