### ISSUE TITLE
[UST-253][Feature][Frontend] Add Epoch Key Explanation link in Records Page Table

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#542]
## Description

- 在Epoch key 上面新增?符號，點擊後會跳到平台說明中的Epoch / Epoch Key / 動作操作計數區(https://www.figma.com/design/WFpSKfe9741XSlXkOXz8s0/Unirep-Social?node-id=3846-8258&node-type=canvas)

![我的帳號優化4 (1)](https://github.com/user-attachments/assets/af070dc0-2377-40f1-8ee2-fac206cfd943)
![我的帳號優化5 (1)](https://github.com/user-attachments/assets/02614fb9-50bd-47e2-9f65-0ff9aaffdf45)
![image (8)](https://github.com/user-attachments/assets/ad989a5f-b7b1-4b34-b94a-ceb1b2a16fa9)

- Story Point: 1
- Reporter: @UranusLin

**Comment by cc03668** [comment]
@UranusLin 請更新 description
