### ISSUE TITLE
Wait for the transaction to finalize in relay test

### ISSUE THREAD

**Issue by ryanycw** [social-tw/social-tw-website#55]
**Describe the bug**
In #25 the hardhat test won't wait for post transaction to finish. Need to find a way to wait for the transaction to finish. And make sure the synchronizer have get the transaction and update the db.

**To Reproduce**
`yarn relay test`

**Expected behavior**
```
it('should create a post', async () => {
    // FIXME: Look for fuzzer to test content
    const testContent = 'test content'

    const epochKeyProof = await userState.genEpochKeyProof({
        nonce: 0,
    })

    const res = await fetch(`${HTTP_SERVER}/api/post`, {
        method: 'POST',
        headers: {
            'content-type': 'application/json',
        },
        body: JSON.stringify(
            stringifyBigInts({
                content: testContent,
                publicSignals: epochKeyProof.publicSignals,
                proof: epochKeyProof.proof,
            })
        ),
    }).then((r) => r.json())
    //expect(res.status).equal(200)
    //expect(res.body).('postId')
    // TODO: verify post
    // [ ] verify transaction
    // [ ] fetch post
})
```
Make sure this test passed with the right checks, finishing the TODO

**Additional context**

**Comment by ryanycw** [comment]
@andy78644 Do you have any progress on this? Cause I've solved my previous problem, and I can jump in to work on this with you.

**Comment by andy78644** [comment]
@ryanycw Just start. I think I can finish it today

**Comment by ryanycw** [comment]
@andy78644 I believe I've just solved it! Let me push the code in a bit, see if there is anything you want to solve.

**Comment by ryanycw** [comment]
I will close this issue for now, feel free to open new issue if there is anything to be fixed.
