### ISSUE TITLE
abstract code inside async load()

### ISSUE THREAD

**Issue by NOOMA-42** [social-tw/social-tw-website#56]
**Is your feature request related to a problem? Please describe.**
`load()` is in `context/User.ts`  can be tricking during testing. Test case have to copy from `load()` and replace some code manually

**Describe the solution you'd like**
Abstract the code in `User.ts` from
```
const identity = new Identity(this.signature)
        const {UNIREP_ADDRESS, APP_ADDRESS, ETH_PROVIDER_URL} = await fetch(
            `${SERVER}/api/config`
        ).then((r) => r.json())
.......
```

**Describe alternatives you've considered**
N/A

**Additional context**
Do this after #38 merged

**Comment by badukwei** [comment]
This seems be updated @NOOMA-42
