### ISSUE TITLE
hardhat can't find ts-node

### ISSUE THREAD

**Issue by ryanycw** [social-tw/social-tw-website#58]
**Describe the bug**
In the release/integrate_0713 `yarn && yarn build` works as expected. However in test/post-relay, it requires to use node18. And when running `yarn && yarn build` from scratch, the following error occur.

**To Reproduce**
In test/post-relay, `yarn && yarn build`. 
And if `cd packages/contracts/` and `yarn add --dev ts-node`.
The `yarn build ` works

P.S. Use `yarn contracts hardhat node` and `yarn contracts deploy` to generate config.ts first

**Expected behavior**
https://app.warp.dev/block/TBQW9C3KUJf7pnjXrj0E4l
https://app.warp.dev/block/1diqb5rZmF17qG02cs68jI

**Screenshots**
<img width="715" alt="image" src="https://github.com/social-tw/social-tw-website/assets/63644531/a0e10f2b-2b42-4e6a-9e69-75a8549079fe">

**Comment by ryanycw** [comment]
It seems like the hardhat in the global package.json is used in `yarn build`, so it can't find the right ts-node in each folder.
https://github.com/social-tw/social-tw-website/blob/a03f0e785e533e3273349d60d84aec47d4003942/package.json#L25

**Comment by chentihe** [comment]
@node should be removed on package.json under relay folder
https://github.com/social-tw/social-tw-website/blob/test/post-relay/packages/relay/package.json#L19
https://github.com/social-tw/social-tw-website/blob/test/post-relay/packages/relay/package.json#L34

besides, in post test, the type of every response is unknown, should be modified to specific type.
I just set the type of all res to any, you can add the interface to replace the type later

**Comment by ryanycw** [comment]
> @node should be removed on package.json under relay folder https://github.com/social-tw/social-tw-website/blob/test/post-relay/packages/relay/package.json#L19 https://github.com/social-tw/social-tw-website/blob/test/post-relay/packages/relay/package.json#L34
> 
> besides, in post test, the type of every response is unknown, should be modified to specific type. I just set the type of all res to any, you can add the interface to replace the type later

This is on me, it seems that I've created this mistake while solving the conflicts with release/integrate.
https://github.com/social-tw/social-tw-website/commit/2912594854abdc3f327d0c52a112c5e1b10d1e39

I am closing this issue, feel free to open a new one if any other issue occurs.
