### ISSUE TITLE
IPFS local environment setting

### ISSUE THREAD

**Issue by badukwei** [social-tw/social-tw-website#65]
**Describe the bug**

While calling api/post, the bug occurs. The error is about IFPS and some setting with connecting.

**To Reproduce**

1. Login the account
2. Enter text to crate post
3. Create a post

**Expected behavior**

It shouldn't return status 500 when calling api/post

**Screenshots**

![image](https://github.com/social-tw/social-tw-website/assets/109848154/dbc53c4c-73c5-49d1-ab2c-b2b63a181c5d)

**Desktop (please complete the following information):**

 - OS: [Windows (WSL)]

**Comment by andy78644** [comment]
This is old version for IPFS node. New version is in branch test/post-relay

**Comment by ryanycw** [comment]
@badukwei Is this issue still valid?

**Comment by badukwei** [comment]
Yes now it's working totally fine
