### ISSUE TITLE
Cannot signup properly

### ISSUE THREAD

**Issue by chentihe** [social-tw/social-tw-website#66]
**Describe the bug**
When calling `http://localhost:3000/login` to do the sign up flow, invalid hash error will occur after `api/signup`.

**To Reproduce**
Steps to reproduce the behavior

1. checkout to main branch
2. start all servers
3. navigate to `http://localhost:3000/api/login`
4. login with twitter
5. signup with either wallet or server

**Expected behavior**
console log should display `has signed up`

**Screenshots**
![messageImage_1693532463091](https://github.com/social-tw/social-tw-website/assets/48288259/8733d87e-bf7a-464c-aaca-ddb8cdf1919f)

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser Edge
-   Version 116.0.1938.62

**Comment by ryanycw** [comment]
This should be close by #64
