### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by vivianjeng** [social-tw/social-tw-website#68]
We need to update the current readme to help developers install/run the repo locally
- [ ] Introduction to the project (unirep social taiwan)
- [ ] How to install
- [ ] How to build
- [ ] How to run contracts/relay/frontend
- [ ] How to run test/lint
- [ ] How to contribute to this project
- [ ] How to contact us (discord, open issues, ....)
- [ ] (optional) a banner
- [ ] (optional) if CI/CD succeeds
- [ ] (optional) package version

**Comment by ryanycw** [comment]
This is closed with #90.
