### ISSUE TITLE
different commitments between proof and identity

### ISSUE THREAD

**Issue by chentihe** [social-tw/social-tw-website#73]
**Describe the bug**
we use signature(wallet signs the hash user id) as constructor arg of semaphore identity.
when the user signs up, signature will be store at local storage on frontend to initiate the identity.
after signup event emitted, the db will store user signup data.

However, when we refresh the page, we cannot find out the UserSignUp data by the commitment which is derived by the signature. we found out that the commitment is different between the proof and the identity.

**To Reproduce**

1. checkout to branch feature/signup-status-ui
2. start the server
3. navigate to `http://localhost:3000`
4. finish the sign up flow (clean the local storage if you don't see the twitter login page)
5. open the console, refresh the page once you see `has signed up` message

**Expected behavior**
no error message shows up on the console

**Screenshots**
![image](https://github.com/social-tw/social-tw-website/assets/48288259/8db6ebf5-cc6b-4977-a8c3-e731831f511e)
the commitment from identity: 21522971102930138771970627849125848578287951763320037973197264532156976505989n
the commitment from db:
2621895226801663766506515946213190338996256122790072923134401166554411614480

**Desktop (please complete the following information):**

-   OS: maxOS
-   Browser edge
-   Version 116.0.1938.62

**Comment by vivianjeng** [comment]
I think it is the bug of `create-unirep-app` 😢 
https://github.com/social-tw/social-tw-website/blob/6952f66154bdfb304401e9d2a24d9758b511ad87/packages/frontend/src/contexts/User.tsx#L84

If you clean the storage
it will assign your id as `''`
so the commitment of `new Identity('')` is `2621895226801663766506515946213190338996256122790072923134401166554411614480` itself

**Comment by chentihe** [comment]
Thanks for the help, I'll close this issue
