### ISSUE TITLE
Ci failed of Lint job

### ISSUE THREAD

**Issue by chentihe** [social-tw/social-tw-website#92]
**Describe the bug**
Something went wrong with Lint Ci Job, there's no modification on `.github/PULL_REQUEST_TEMPLATE.md` `CONTRIBUTING.md`, but these two files didn't pass the lint job

**To Reproduce**

1. check to feature/combine-init-and-signup-behavior
2. push commit to remote

**Expected behavior**
Lint ci job should success

**Screenshots**
![image](https://github.com/social-tw/social-tw-website/assets/48288259/9418de90-544e-4d90-8b6a-92028b538e94)

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Comment by jason-ntu** [comment]
Had you run `yarn lint:fix` before the PR~?

**Comment by ryanycw** [comment]
I believe it is fixed now. The reason that this happens is because some files on main haven't passed through the linter.
