### ISSUE TITLE
[contract][relay] verify state tree root, caller, epoch

### ISSUE THREAD

**Issue by vivianjeng** [social-tw/social-tw-website#95]
In 2.0.0-beta-4, we move out the `EpochKeyVerifier` from `Unirep.sol` to minimize the core contract size.
But it doesn't check the state tree root (so users might be able to randomly generated a proof without the current Unirep merkle tree), and current epoch.
See [VerifyAndCheckCaller](https://developer.unirep.io/docs/contracts-api/verifiers/epoch-key-verifier-helper#verifyandcheckcaller)

**Suggestion**

*Contract*
https://github.com/social-tw/social-tw-website/blob/6e45b3b3dcd324fddeebc9e64421f5c644cb879d/packages/contracts/contracts/UnirepApp.sol#L88-L92

- Use `verifyAndCheckCaller` to replace `verifyAndCheck`
- Check epoch with [`attesterCurrentEpoch`](https://developer.unirep.io/docs/contracts-api/unirep-sol#attestercurrentepoch)
- Check state tree root with [`attesterStateTreeRootExists`](https://developer.unirep.io/docs/contracts-api/unirep-sol#attesterstatetreerootexists)

*Relay*
This check would prevent submitting tx would be reverted and faster respond to clients.
https://github.com/social-tw/social-tw-website/blob/6e45b3b3dcd324fddeebc9e64421f5c644cb879d/packages/relay/src/routes/post.ts#L72-L82
- Check epoch with [`synchronizer.loadCurrentEpoch()`](https://developer.unirep.io/docs/core-api/synchronizer#loadcurrentepoch)
- Check state tree root with [`synchronizer.stateTreeRootExists`](https://developer.unirep.io/docs/core-api/synchronizer#statetreerootexists)

**Comment by FoodChain1028** [comment]
i would like to deal with this

**Comment by vivianjeng** [comment]
@FoodChain1028 FYI
I think the verifier helpers should be changed like this https://github.com/Unirep/Unirep/pull/549
So in the future the contract won't check the epoch and state tree root
(but the relayer still needs to check)
